# dataset
data_dir: /mnt/data/datasets/CIFAR10
dataset: torch/cifar10
num_classes: 10
img_size: 32

#data augmentation
mean:
    - 0.4914
    - 0.4822
    - 0.4465
std:
    - 0.2470
    - 0.2435
    - 0.2616
crop_pct: 1.0
scale:
    - 1.0
    - 1.0
ratio: [1.0, 1.0]
interpolation: bicubic
train_interpolation: bicubic
aa: rand-m9-n1-mstd0.4-inc1
color_jitter: 0.5
epochs: 300   #epochs
mixup: 0.5
mixup_off_epoch: 200
mixup_prob: 1.0
mixup_mode: batch
mixup_switch_prob: 0.5
cutmix: 0.0

model-ema: False
model-ema-decay: 0.9998

#model structure
model: "std_cifar"
step: 4
patch_size: 4
in_channels: 3
embed_dim: 512
num_heads: 8
mlp_ratio: 4
attn_scale: 0.125
mlp_drop: 0.0
attn_drop: 0.0
depths: 2

# node
tau: 2.0
threshold: 1.0
act_function: SigmoidGrad
node_type: ComplementaryLIFNeuron
alpha: 4.0

# train hyperparam
amp: False
channels-last: False
batch_size: 64
val_batch_size: 64
lr: 3e-4
min_lr: 1e-5
sched: cosine
weight_decay: 6e-2
cooldown_epochs: 10
warmup_epochs: 20
warmup_lr:  1e-6
opt: adamw
smoothing: 0.1
workers: 8
seed: 42
log_interval: 200

# device
device: 0

# log dir
output: "/mnt/home/fenglinghao/log/SpikingTransformerBenchmark/cls/neuron_model"
